# Generated by Django 2.0.10 on 2019-06-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssDealTypeParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(max_length=100, unique=True)),
                ('long_probability', models.FloatField(null=True)),
                ('long_irr', models.FloatField(null=True)),
                ('long_max_risk', models.FloatField(null=True)),
                ('long_max_size', models.FloatField(null=True)),
                ('short_probability', models.FloatField(null=True)),
                ('short_irr', models.FloatField(null=True)),
                ('short_max_risk', models.FloatField(null=True)),
                ('short_max_size', models.FloatField(null=True)),
            ],
        ),
    ]
