# Generated by Django 2.0.10 on 2019-06-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedSizingByRiskAdjProb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arb_max_risk', models.FloatField()),
                ('win_probability', models.FloatField()),
                ('lose_probability', models.FloatField()),
                ('risk_adj_loss', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SoftCatalystNormalizedRiskSizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=10)),
                ('win_probability', models.FloatField()),
                ('lose_probability', models.FloatField()),
                ('max_risk', models.FloatField()),
                ('avg_position', models.FloatField()),
            ],
        ),
    ]
