# Generated by Django 2.0.10 on 2019-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0003_esspotentiallongshorts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssUniverseImpliedProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('deal_type', models.CharField(max_length=100, null=True)),
                ('implied_probability', models.FloatField(null=True)),
            ],
        ),
    ]
