# Generated by Django 2.0.10 on 2019-06-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0004_essuniverseimpliedprobability'),
    ]

    operations = [
        migrations.AddField(
            model_name='essuniverseimpliedprobability',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
