# Generated by Django 2.0.10 on 2019-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0005_essuniverseimpliedprobability_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='esspotentiallongshorts',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
