# Generated by Django 2.0.13 on 2019-06-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0006_esspotentiallongshorts_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EssDealTypearameters',
            new_name='EssDealTypeParameters',
        ),
    ]
