# Generated by Django 2.0.10 on 2019-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0007_auto_20190618_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='esspotentiallongshorts',
            name='ess_idea_id',
            field=models.IntegerField(default=-999),
            preserve_default=False,
        ),
    ]
