# Generated by Django 2.0.10 on 2019-07-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0010_auto_20190701_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arboptimizationuniverse',
            old_name='target_last_px',
            new_name='target_last_price',
        ),
        migrations.RenameField(
            model_name='arboptimizationuniverse',
            old_name='tradeGroup',
            new_name='tradegroup',
        ),
    ]
