# Generated by Django 2.0.10 on 2019-07-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0011_auto_20190701_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arboptimizationuniverse',
            old_name='deal_upside',
            new_name='deal_value',
        ),
    ]
