# Generated by Django 2.0.10 on 2019-07-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0013_arboptimizationuniverse_gross_hedge_ror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arboptimizationuniverse',
            old_name='gross_hedge_ror',
            new_name='pnl_impact',
        ),
    ]
