# Generated by Django 2.0.10 on 2019-07-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0014_auto_20190709_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardFloatOptimization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField()),
                ('tradegroup', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=50)),
                ('bucket', models.CharField(max_length=50)),
                ('catalyst', models.CharField(max_length=50, null=True)),
                ('catalyst_rating', models.CharField(max_length=5, null=True)),
                ('closing_date', models.DateField(null=True)),
                ('target_ticker', models.CharField(max_length=100, null=True)),
                ('long_short', models.CharField(max_length=50, null=True)),
                ('target_last_price', models.FloatField(null=True)),
                ('deal_value', models.FloatField(null=True)),
                ('pnl_impact', models.FloatField(null=True)),
                ('all_in_spread', models.FloatField(null=True)),
                ('deal_downside', models.FloatField(null=True)),
                ('days_to_close', models.IntegerField(null=True)),
                ('pct_of_sleeve_current', models.FloatField(null=True)),
                ('gross_ror', models.FloatField(null=True)),
                ('ann_ror', models.FloatField(null=True)),
                ('base_case_nav_impact', models.FloatField(null=True)),
                ('risk_pct', models.FloatField(null=True)),
                ('expected_vol', models.FloatField(null=True)),
                ('total_qty', models.FloatField(null=True)),
                ('total_qty_1x', models.FloatField(null=True)),
                ('total_qty_2x', models.FloatField(null=True)),
                ('eqy_float', models.FloatField(null=True)),
                ('current_pct_of_float', models.FloatField(null=True)),
                ('firm_pct_float_mstrat_1x', models.FloatField(null=True)),
                ('firm_pct_float_mstrat_2x', models.FloatField(null=True)),
                ('aed_aum_mult', models.FloatField(null=True)),
                ('lg_aum_mult', models.FloatField(null=True)),
            ],
        ),
    ]
