# Generated by Django 2.0.10 on 2019-07-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0015_hardfloatoptimization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='all_in_spread',
        ),
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='base_case_nav_impact',
        ),
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='deal_downside',
        ),
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='long_short',
        ),
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='pct_of_sleeve_current',
        ),
        migrations.RemoveField(
            model_name='hardfloatoptimization',
            name='pnl_impact',
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
