# Generated by Django 2.0.10 on 2019-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0016_auto_20190711_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='all_in_spread',
            field=models.FloatField(null=True),
        ),
    ]
