# Generated by Django 2.0.10 on 2019-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0017_hardfloatoptimization_all_in_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='aed_risk_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='lg_risk_mult',
            field=models.FloatField(null=True),
        ),
    ]
