# Generated by Django 2.0.10 on 2019-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0018_auto_20190711_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='aed_outier_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='arb_outlier_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='lg_outlier_risk',
            field=models.FloatField(null=True),
        ),
    ]
