# Generated by Django 2.0.10 on 2019-07-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0019_auto_20190711_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardfloatoptimization',
            old_name='aed_outier_risk',
            new_name='aed_outlier_risk',
        ),
    ]
