# Generated by Django 2.0.10 on 2019-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0020_auto_20190711_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='aed_pct_of_aum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='arb_pct_of_aum',
            field=models.FloatField(null=True),
        ),
    ]
