# Generated by Django 2.0.10 on 2019-07-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0021_auto_20190712_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='rebal_multiples',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='rebal_target',
            field=models.FloatField(null=True),
        ),
    ]
