# Generated by Django 2.0.10 on 2019-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0022_auto_20190712_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='curr_rtn_wt_duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='curr_rwd_ror',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='non_excluded_pct_aum_cumsum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='weighted_gross_nav_potential',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hardfloatoptimization',
            name='weighted_nav_cumsum',
            field=models.FloatField(null=True),
        ),
    ]
