# Generated by Django 2.0.10 on 2019-07-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_optimization', '0023_auto_20190716_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardOptimizationSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField()),
                ('average_optimized_rors', models.FloatField(null=True)),
                ('weighted_arb_rors', models.FloatField(null=True)),
                ('weighted_aed_ror', models.FloatField(null=True)),
                ('arb_number_of_deals', models.IntegerField(null=True)),
                ('arb_pct_invested', models.FloatField(null=True)),
                ('aed_number_of_deals', models.IntegerField(null=True)),
                ('aed_hard_pct_invested', models.FloatField(null=True)),
                ('aed_fund_pct_invested', models.FloatField(null=True)),
                ('aed_currently_invested', models.FloatField(null=True)),
            ],
        ),
    ]
