# Generated by Django 2.0.13 on 2019-05-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFundPositionRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=10, null=True)),
                ('mnemonic', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('fund', models.CharField(blank=True, max_length=10, null=True)),
                ('excluded', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100, null=True)),
                ('date_updated', models.DateTimeField()),
            ],
        ),
    ]
