# Generated by Django 2.0.13 on 2019-05-31 14:25

from django.db import migrations, models
import position_rec.models


class Migration(migrations.Migration):

    dependencies = [
        ('position_rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRecAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_rec_attachment', models.FileField(null=True, upload_to=position_rec.models.get_position_rec_path_filename)),
                ('original_filename', models.CharField(default='filename', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.CharField(max_length=100, null=True)),
                ('uploaded_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
