# Generated by Django 2.0.13 on 2019-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_rec', '0002_positionrecattachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRecBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party', models.CharField(blank=True, max_length=255, null=True)),
                ('fund', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker', models.CharField(blank=True, max_length=255, null=True)),
                ('tradar_quantity', models.IntegerField(default=0)),
                ('trade_date_quantity', models.IntegerField(default=0)),
                ('account_no', models.CharField(max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('is_resolved', models.BooleanField()),
                ('is_break', models.BooleanField()),
                ('number_of_days', models.IntegerField(default=0)),
            ],
        ),
    ]
