# Generated by Django 2.0.13 on 2019-06-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_rec', '0003_positionrecbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionrecbreak',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
