# Generated by Django 2.0.6 on 2018-12-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_creditdatabase_ma_deals_ma_deals_lawyer_reports_ma_deals_notes_ma_deals_peerset_ma_deals_scenario_an'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ess_peers',
            name='version_number',
        ),
    ]
