# Generated by Django 2.0.10 on 2019-04-30 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20190416_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ess_idea',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 11, 16, 24, 985627), null=True),
        ),
        migrations.AlterField(
            model_name='ess_idea_upside_downside_change_records',
            name='date_updated',
            field=models.DateTimeField(),
        ),
    ]
