# Generated by Django 2.0.6 on 2018-12-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_remove_ess_peers_version_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ess_idea',
            unique_together=set(),
        ),
    ]
