# Generated by Django 2.0.13 on 2019-05-21 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20190509_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MA_Deals_Scenario_Analysis',
        ),
    ]
