# Generated by Django 2.0.6 on 2018-12-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20181207_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_peers',
            name='version_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ess_peers',
            unique_together={('id', 'version_number')},
        ),
    ]
