# Generated by Django 2.0.13 on 2019-05-23 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20190521_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaDealsActionIdDetails',
            fields=[
                ('action_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, max_length=100, null=True)),
                ('target_ticker', models.CharField(blank=True, max_length=100, null=True)),
                ('target_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('target_country', models.CharField(blank=True, max_length=100, null=True)),
                ('acquirer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('acquirer_ticker', models.CharField(blank=True, max_length=100, null=True)),
                ('acquirer_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('acquirer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('deal_status', models.CharField(blank=True, max_length=100, null=True)),
                ('nature_of_bid', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('announced_date', models.DateField(blank=True, null=True)),
                ('mergers_agreement_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('drop_dead_date', models.DateField(blank=True, null=True)),
                ('go_shop_period_end_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('net_debt', models.CharField(blank=True, max_length=200, null=True)),
                ('ebitda_total_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('ebit_total_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('revenue_total_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('total_assets_total_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('free_cashflow_total_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('ebitda_equity_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('ebit_equity_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('revenue_equity_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('total_assets_equity_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('free_cashflow_equity_tvm', models.CharField(blank=True, max_length=200, null=True)),
                ('deal_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('stock_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('percent_owned', models.CharField(blank=True, max_length=200, null=True)),
                ('percent_sought', models.CharField(blank=True, max_length=200, null=True)),
                ('announced_total_value', models.CharField(blank=True, max_length=200, null=True)),
                ('announced_premium', models.CharField(blank=True, max_length=200, null=True)),
                ('target_to_acquirer_termination_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('acquirer_to_target_termination_fess', models.CharField(blank=True, max_length=200, null=True)),
                ('pending_approvals', models.CharField(blank=True, max_length=200, null=True)),
                ('expired_approvals', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_approvals', models.CharField(blank=True, max_length=200, null=True)),
                ('extended_approvals', models.CharField(blank=True, max_length=200, null=True)),
                ('blocked_approvals', models.CharField(blank=True, max_length=200, null=True)),
                ('early_termination_approvals', models.CharField(blank=True, max_length=200, null=True)),
                ('deal_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
