# Generated by Django 2.0.13 on 2019-06-19 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20190523_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_idea',
            name='tradegroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
