# Generated by Django 2.0.6 on 2018-12-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20181210_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ess_idea',
            name='peers',
        ),
        migrations.AddField(
            model_name='ess_peers',
            name='ess_idea_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.ESS_Idea'),
        ),
    ]
