# Generated by Django 2.0.13 on 2019-06-24 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20190620_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_idea',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
