# Generated by Django 2.0.6 on 2018-12-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20181211_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_idea',
            name='deal_key',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
