# Generated by Django 2.0.6 on 2018-12-12 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_ess_idea_idea_balance_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESS_Idea_Upside_Downside_Change_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_key', models.IntegerField(null=True)),
                ('pt_up', models.FloatField(null=True)),
                ('pt_wic', models.FloatField(null=True)),
                ('pt_down', models.FloatField(null=True)),
                ('date_updated', models.DateField()),
                ('ess_idea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ESS_Idea')),
            ],
        ),
    ]
