# Generated by Django 2.0.6 on 2018-12-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_ess_idea_upside_downside_change_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ess_idea',
            name='bear_thesis_model',
            field=models.FileField(default='NA', upload_to='ESS_IDEA_MODELS/BEAR_THESIS/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='ess_idea',
            name='bull_thesis_model',
            field=models.FileField(default='NA', upload_to='ESS_IDEA_MODELS/BULL_THESIS/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='ess_idea',
            name='our_thesis_model',
            field=models.FileField(default='NA', upload_to='ESS_IDEA_MODELS/OUR_THESIS/%Y%m%d'),
        ),
    ]
