# Generated by Django 2.0.6 on 2019-01-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_auto_20181212_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_idea',
            name='pt_down_check',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ess_idea',
            name='pt_up_check',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ess_idea',
            name='pt_wic_check',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
