# Generated by Django 2.0.10 on 2019-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_auto_20190114_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_idea',
            name='on_pt_balance_sheet',
            field=models.TextField(null=True),
        ),
    ]
