# Generated by Django 2.0.10 on 2019-02-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_auto_20190123_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_deals_peerset',
            name='ev_sales_chart_1bf',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ma_deals_peerset',
            name='ev_sales_chart_2bf',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ma_deals_peerset',
            name='ev_sales_chart_ltm',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
