# Generated by Django 2.0.10 on 2019-02-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_auto_20190214_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESS_Idea_BearFileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_key', models.IntegerField(null=True)),
                ('bear_thesis_model', models.FileField(null=True, upload_to='')),
                ('uploaded_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESS_Idea_BullFileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_key', models.IntegerField(null=True)),
                ('bull_thesis_model', models.FileField(null=True, upload_to='')),
                ('uploaded_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESS_Idea_OurFileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_key', models.IntegerField(null=True)),
                ('our_thesis_model', models.FileField(null=True, upload_to='')),
                ('uploaded_at', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ess_idea',
            name='bear_thesis_model',
        ),
        migrations.RemoveField(
            model_name='ess_idea',
            name='bull_thesis_model',
        ),
        migrations.RemoveField(
            model_name='ess_idea',
            name='our_thesis_model',
        ),
        migrations.AddField(
            model_name='ess_idea_ourfileuploads',
            name='ess_idea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ESS_Idea'),
        ),
        migrations.AddField(
            model_name='ess_idea_bullfileuploads',
            name='ess_idea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ESS_Idea'),
        ),
        migrations.AddField(
            model_name='ess_idea_bearfileuploads',
            name='ess_idea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ESS_Idea'),
        ),
    ]
