# Generated by Django 2.0.10 on 2019-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_auto_20190219_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ess_idea_bearfileuploads',
            name='bear_thesis_model',
            field=models.FileField(null=True, upload_to='ESS_IDEA_DB_FILES/BEAR_THESIS_FILES'),
        ),
        migrations.AlterField(
            model_name='ess_idea_bullfileuploads',
            name='bull_thesis_model',
            field=models.FileField(null=True, upload_to='ESS_IDEA_DB_FILES/BULL_THESIS_FILES'),
        ),
        migrations.AlterField(
            model_name='ess_idea_ourfileuploads',
            name='our_thesis_model',
            field=models.FileField(null=True, upload_to='ESS_IDEA_DB_FILES/OUR_THESIS_FILES'),
        ),
    ]
