# Generated by Django 2.0.10 on 2019-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0019_auto_20190220_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma_deals',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
