# Generated by Django 2.0.10 on 2019-02-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_ma_deals_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ma_deals',
            name='last_downside_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals',
            name='last_modified',
            field=models.DateField(default=None),
        ),
    ]
