# Generated by Django 2.0.10 on 2019-02-28 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0021_auto_20190221_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='MA_Deals_Risk_Factors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definiteness', models.CharField(max_length=100, null=True)),
                ('hostile_friendly', models.CharField(max_length=10, null=True)),
                ('strategic_pe', models.CharField(max_length=10, null=True)),
                ('deal_rationale', models.CharField(max_length=100, null=True)),
                ('premium_percentage', models.CharField(max_length=10, null=True)),
                ('stock_cash', models.CharField(max_length=100, null=True)),
                ('financing_percent_of_deal_value', models.CharField(max_length=10, null=True)),
                ('pro_forma_leverage', models.CharField(max_length=50, null=True)),
                ('estimated_closing_date', models.DateField(null=True)),
                ('go_shop', models.CharField(max_length=5, null=True)),
                ('divestitures_required', models.CharField(max_length=15, null=True)),
                ('termination_fee_for_acquirer', models.FloatField(null=True)),
                ('termination_fee_for_target', models.FloatField(null=True)),
                ('fair_valuation', models.CharField(max_length=30, null=True)),
                ('cyclical_industry', models.CharField(max_length=5, null=True)),
                ('sec_requirement', models.CharField(max_length=15, null=True)),
                ('sec_expected_clearance', models.DateField(null=True)),
                ('sec_actual_clearance', models.DateField(null=True)),
                ('hsr_requirement', models.CharField(max_length=15, null=True)),
                ('hsr_expected_clearance', models.DateField(null=True)),
                ('hsr_actual_clearance', models.DateField(null=True)),
                ('mofcom_requirement', models.CharField(max_length=15, null=True)),
                ('mofcom_expected_clearance', models.DateField(null=True)),
                ('mofcom_actual_clearance', models.DateField(null=True)),
                ('cifius_requirement', models.CharField(max_length=15, null=True)),
                ('cifius_expected_clearance', models.DateField(null=True)),
                ('cifius_actual_clearance', models.DateField(null=True)),
                ('ec_requirement', models.CharField(max_length=15, null=True)),
                ('ec_expected_clearance', models.DateField(null=True)),
                ('ec_actual_clearance', models.DateField(null=True)),
                ('accc_requirement', models.CharField(max_length=15, null=True)),
                ('accc_expected_clearance', models.DateField(null=True)),
                ('accc_actual_clearance', models.DateField(null=True)),
                ('investment_canada_requirement', models.CharField(max_length=15, null=True)),
                ('investment_canada_expected_clearance', models.DateField(null=True)),
                ('investment_canada_actual_clearance', models.DateField(null=True)),
                ('cade_requirement', models.CharField(max_length=15, null=True)),
                ('cade_expected_clearance', models.DateField(null=True)),
                ('cade_actual_clearance', models.DateField(null=True)),
                ('other_country_regulatory_risk_one', models.CharField(max_length=50, null=True)),
                ('other_country_regulatory_risk_two', models.CharField(max_length=50, null=True)),
                ('acquirer_sh_vote_required', models.CharField(max_length=15, null=True)),
                ('target_sh_vote_required_percentage', models.CharField(max_length=100, null=True)),
                ('acquirer_becomes_target', models.CharField(max_length=50, null=True)),
                ('potential_bidding_war', models.CharField(max_length=50, null=True)),
                ('commodity_risk', models.CharField(max_length=50, null=True)),
                ('estimated_market_share_acquirer', models.CharField(max_length=50, null=True)),
                ('estimated_market_share_target', models.CharField(max_length=50, null=True)),
                ('is_iversion_deal_or_tax_avoidance', models.CharField(max_length=10, null=True)),
                ('activists_involved', models.TextField(null=True)),
                ('is_form_complete', models.CharField(default='No', max_length=5)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.MA_Deals')),
            ],
        ),
    ]
