# Generated by Django 2.0.10 on 2019-03-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_ma_deals_risk_factors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='accc_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='acquirer_sh_vote_required',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='cade_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='cifius_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='ec_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='hsr_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='investment_canada_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='mofcom_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_risk_factors',
            name='sec_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
