# Generated by Django 2.0.13 on 2019-03-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_auto_20190304_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssIdeaAdjustmentsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_key', models.IntegerField(null=True)),
                ('regression_results', models.TextField(null=True)),
                ('regression_calculations', models.TextField(null=True)),
                ('cix_calculations', models.TextField(null=True)),
                ('calculated_on', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ess_idea',
            old_name='idea_balance_sheet',
            new_name='downside_balance_sheet',
        ),
        migrations.RenameField(
            model_name='ess_idea',
            old_name='on_pt_balance_sheet',
            new_name='upside_balance_sheet',
        ),
        migrations.RemoveField(
            model_name='ma_deals_lawyer_reports',
            name='analyst_rating',
        ),
        migrations.AddField(
            model_name='ess_idea',
            name='wic_balance_sheet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ma_deals_lawyer_reports',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_lawyer_reports',
            name='analyst_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_lawyer_reports',
            name='lawyer_report',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ma_deals_lawyer_reports',
            name='lawyer_report_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='essideaadjustmentsinformation',
            name='ess_idea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.ESS_Idea'),
        ),
    ]
