# Generated by Django 2.0.13 on 2019-04-04 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import risk.models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_auto_20190304_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ess_idea_bearfileuploads',
            name='original_filename',
            field=models.CharField(default='filename', max_length=100),
        ),
        migrations.AddField(
            model_name='ess_idea_bullfileuploads',
            name='original_filename',
            field=models.CharField(default='filename', max_length=100),
        ),
        migrations.AddField(
            model_name='ess_idea_ourfileuploads',
            name='original_filename',
            field=models.CharField(default='filename', max_length=100),
        ),
        migrations.AlterField(
            model_name='ess_idea_bearfileuploads',
            name='bear_thesis_model',
            field=models.FileField(null=True, upload_to=risk.models.get_bearfile_path_filename),
        ),
        migrations.AlterField(
            model_name='ess_idea_bullfileuploads',
            name='bull_thesis_model',
            field=models.FileField(null=True, upload_to=risk.models.get_bullfile_path_filename),
        ),
        migrations.AlterField(
            model_name='ess_idea_ourfileuploads',
            name='our_thesis_model',
            field=models.FileField(null=True, upload_to=risk.models.get_ourfile_path_filename),
        ),
    ]
