# Generated by Django 2.0.13 on 2019-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=200)),
                ('cash_terms', models.FloatField(null=True)),
                ('stock_terms', models.FloatField(null=True)),
                ('number_of_target_dividends', models.CharField(max_length=100, null=True)),
                ('number_of_acquirer_dividends', models.CharField(max_length=100, null=True)),
                ('target_dividend_rate', models.CharField(max_length=100, null=True)),
                ('acquirer_dividend_rate', models.CharField(max_length=100, null=True)),
                ('closing_date', models.DateField(null=True)),
            ],
        ),
    ]
