# Generated by Django 2.0.13 on 2019-04-05 16:43

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_attachment', models.FileField(null=True, upload_to=notes.models.get_notes_path_filename)),
                ('original_filename', models.CharField(default='filename', max_length=100)),
                ('uploaded_on', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotesMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('article', models.TextField()),
                ('tickers', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='notesattachments',
            name='notes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.NotesMaster'),
        ),
    ]
