# Generated by Django 2.0.3 on 2018-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('article', models.TextField()),
                ('tickers', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NotesAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_attachment', models.FileField(null=True, upload_to="NOTES_ATTACHMENTS")),
                ('uploaded_on', models.DateField(null=True)),
                ('notes_id', models.ForeignKey(on_delete=models.deletion.CASCADE, to='notes.NotesMaster')),
            ],
        ),
    ]
