# Generated by Django 2.0.13 on 2019-03-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=1000)),
                ('article', models.TextField()),
                ('tickers', models.CharField(max_length=1000)),
                ('notes_attachment', models.FileField(null=True, upload_to='NOTES_ATTACHMENTS')),
                ('notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.NotesMaster')),
            ],
        ),
    ]
