# Generated by Django 2.0.13 on 2019-06-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmaster',
            name='is_sleeve_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notesmaster',
            name='is_sleeve_ess',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notesmaster',
            name='is_sleeve_mna',
            field=models.BooleanField(default=False),
        ),
    ]
