# Generated by Django 2.0.13 on 2019-04-04 17:03

from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesattachments',
            name='original_filename',
            field=models.CharField(default='filename', max_length=100),
        ),
        migrations.AlterField(
            model_name='notesattachments',
            name='notes_attachment',
            field=models.FileField(null=True, upload_to=notes.models.get_notes_path_filename),
        ),
    ]
