# Generated by Django 2.0.6 on 2018-10-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=50)),
                ('underlying_ticker', models.CharField(max_length=30)),
                ('target_acquirer', models.CharField(max_length=8)),
                ('risk_limit', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=6)),
                ('underlying_current_price', models.FloatField()),
                ('downside_base_case', models.FloatField()),
                ('downside_outlier', models.FloatField()),
                ('analyst', models.CharField(max_length=10)),
                ('last_update_date', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
