# Generated by Django 2.0.13 on 2019-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDealsUpsideDownside',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tradegroup', models.CharField(max_length=100, null=True)),
                ('ticker', models.CharField(max_length=100, null=True)),
                ('analyst', models.CharField(max_length=20, null=True)),
                ('origination_date', models.DateField(null=True)),
                ('last_update', models.DateField(null=True)),
                ('spread_index', models.CharField(max_length=50, null=True)),
                ('deal_value', models.FloatField(blank=True, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('is_excluded', models.CharField(default='No', max_length=22)),
                ('risk_limit', models.FloatField(blank=True, null=True)),
                ('downside_type', models.CharField(max_length=50, null=True)),
                ('downside', models.CharField(blank=True, max_length=50, null=True)),
                ('downside_notes', models.TextField(null=True)),
                ('upside_type', models.CharField(max_length=50, null=True)),
                ('upside', models.CharField(blank=True, max_length=50, null=True)),
                ('upside_notes', models.TextField(null=True)),
            ],
        ),
    ]
