# Generated by Django 2.0.6 on 2018-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskattributes',
            name='last_update_date',
            field=models.DateTimeField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='riskattributes',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='riskattributes',
            name='underlying_current_price',
            field=models.FloatField(default=0),
        ),
    ]
