# Generated by Django 2.0.13 on 2019-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0002_creditdealsupsidedownside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdealsupsidedownside',
            name='last_update',
        ),
        migrations.AddField(
            model_name='creditdealsupsidedownside',
            name='bloomberg_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditdealsupsidedownside',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
