# Generated by Django 2.0.13 on 2019-06-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0003_auto_20190607_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdealsupsidedownside',
            name='last_refreshed',
            field=models.DateTimeField(null=True),
        ),
    ]
