# Generated by Django 2.0.6 on 2018-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0004_auto_20181023_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskattributes',
            name='last_update_date',
            field=models.DateTimeField(default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='riskattributes',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
