# Generated by Django 2.0.6 on 2018-11-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0005_auto_20181023_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbNAVImpacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradeDate', models.DateField()),
                ('FundCode', models.CharField(max_length=10)),
                ('TradeGroup', models.CharField(max_length=100)),
                ('Sleeve', models.CharField(max_length=100)),
                ('Bucket', models.CharField(max_length=100)),
                ('Underlying', models.CharField(max_length=100)),
                ('Ticker', models.CharField(max_length=100)),
                ('BloombergGlobalId', models.CharField(max_length=100, null=True)),
                ('SecType', models.CharField(max_length=10, null=True)),
                ('MarketCapCategory', models.CharField(max_length=100, null=True)),
                ('DealTermsCash', models.FloatField(null=True)),
                ('DealTermsStock', models.FloatField(null=True)),
                ('DealValue', models.FloatField(null=True)),
                ('DealClosingDate', models.DateField(null=True)),
                ('AlphaHedge', models.CharField(max_length=50)),
                ('NetMktVal', models.FloatField()),
                ('FxFactor', models.FloatField(null=True)),
                ('Capital', models.FloatField()),
                ('BaseCaseNavImpact', models.FloatField(null=True)),
                ('OutlierNavImpact', models.FloatField(null=True)),
                ('QTY', models.FloatField()),
                ('LongShort', models.CharField(max_length=20)),
                ('CatalystRating', models.FloatField(null=True)),
                ('NAV', models.FloatField(null=True)),
                ('Analyst', models.CharField(max_length=100)),
                ('PM_BASE_CASE', models.FloatField(null=True)),
                ('Outlier', models.FloatField(null=True)),
                ('StrikePrice', models.FloatField(null=True)),
                ('PutCall', models.CharField(max_length=20, null=True)),
                ('LastPrice', models.FloatField(null=True)),
                ('CurrMktVal', models.FloatField(null=True)),
                ('PL_BASE_CASE', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT', models.FloatField(null=True)),
                ('OUTLIER_PL', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT', models.FloatField(null=True)),
            ],
        ),
    ]
