# Generated by Django 2.0.6 on 2018-11-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0007_auto_20181101_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbnavimpacts',
            name='RiskLimit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
