# Generated by Django 2.0.6 on 2018-11-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0008_arbnavimpacts_risklimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNAVImpacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradeGroup', models.CharField(max_length=100)),
                ('RiskLimit', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_AED', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_ARB', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_CAM', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_LEV', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_LG', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_MACO', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_TAQ', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_WED', models.FloatField()),
                ('BASE_CASE_NAV_IMPACT_WIC', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_AED', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_ARB', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_CAM', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_LEV', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_LG', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_MACO', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_TAQ', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_WED', models.FloatField()),
                ('OUTLIER_NAV_IMPACT_WIC', models.FloatField()),
            ],
        ),
    ]
