# Generated by Django 2.0.6 on 2018-11-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0012_auto_20181105_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaeBasedDownsides',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TradeGroup', models.CharField(max_length=100)),
                ('Underlying', models.CharField(max_length=100)),
                ('TargetAcquirer', models.CharField(max_length=14, null=True)),
                ('Analyst', models.CharField(max_length=20, null=True)),
                ('OriginationDate', models.DateField(null=True)),
                ('LastUpdate', models.DateField(null=True)),
                ('LastPrice', models.FloatField()),
                ('IsExluded', models.CharField(max_length=20)),
                ('RiskLimit', models.FloatField(null=True)),
                ('DownsideType', models.CharField(max_length=50, null=True)),
                ('ReferenceDataPoint', models.CharField(max_length=50, null=True)),
                ('ReferencePrice', models.CharField(max_length=50, null=True)),
                ('Operation', models.CharField(max_length=1, null=True)),
                ('CustomInput', models.CharField(max_length=50, null=True)),
                ('Outlier', models.CharField(max_length=50, null=True)),
                ('downside_type_fixed_value', models.FloatField(null=True)),
                ('cix_ticker', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
