# Generated by Django 2.0.6 on 2018-11-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0013_formulaebaseddownsides'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='outlier',
            field=models.FloatField(null=True),
        ),
    ]
