# Generated by Django 2.0.6 on 2018-11-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0015_remove_formulaebaseddownsides_outlier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='Outlier',
            new_name='outlier',
        ),
    ]
