# Generated by Django 2.0.6 on 2018-11-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0016_auto_20181106_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaebaseddownsides',
            name='downside_type_fixed_value',
        ),
    ]
