# Generated by Django 2.0.6 on 2018-11-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0017_remove_formulaebaseddownsides_downside_type_fixed_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='IsExluded',
            new_name='IsExcluded',
        ),
    ]
