# Generated by Django 2.0.6 on 2018-11-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0018_auto_20181106_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='DownsideType',
            new_name='BaseCaseCustomInput',
        ),
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='CustomInput',
            new_name='BaseCaseDownsideType',
        ),
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='Operation',
            new_name='BaseCaseOperation',
        ),
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='ReferenceDataPoint',
            new_name='BaseCaseReferenceDataPoint',
        ),
        migrations.RenameField(
            model_name='formulaebaseddownsides',
            old_name='ReferencePrice',
            new_name='BaseCaseReferencePrice',
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='OutlierCustomInput',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='OutlierDownsideType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='OutlierOperation',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='OutlierReferenceDataPoint',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='OutlierReferencePrice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='base_case',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='base_case_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='outlier_notes',
            field=models.TextField(null=True),
        ),
    ]
