# Generated by Django 2.0.6 on 2018-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0020_auto_20181113_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaebaseddownsides',
            name='DealValue',
            field=models.FloatField(null=True),
        ),
    ]
