# Generated by Django 2.0.6 on 2018-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0021_formulaebaseddownsides_dealvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaebaseddownsides',
            name='LastPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='formulaebaseddownsides',
            name='TradeGroup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulaebaseddownsides',
            name='Underlying',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
