# Generated by Django 2.0.10 on 2019-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0026_auto_20181127_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_MALT',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_MALT',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
