# Generated by Django 2.0.10 on 2019-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0027_auto_20190225_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynavimpacts',
            name='LastUpdate',
            field=models.DateField(null=True),
        ),
    ]
