# Generated by Django 2.0.10 on 2019-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0028_dailynavimpacts_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynavimpacts',
            name='PM_BASE_CASE',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
