# Generated by Django 2.0.10 on 2019-02-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0029_dailynavimpacts_pm_base_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailynavimpacts',
            name='PM_BASE_CASE',
        ),
    ]
