# Generated by Django 2.0.10 on 2019-02-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0030_remove_dailynavimpacts_pm_base_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_WED',
        ),
        migrations.RemoveField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_WIC',
        ),
        migrations.RemoveField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_WED',
        ),
        migrations.RemoveField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_WIC',
        ),
    ]
