# Generated by Django 2.0.10 on 2019-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0031_auto_20190225_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_WED',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_WIC',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_WED',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_WIC',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
