# Generated by Django 2.0.10 on 2019-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0033_auto_20190226_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_WED',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailynavimpacts',
            name='BASE_CASE_NAV_IMPACT_WIC',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_WED',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailynavimpacts',
            name='OUTLIER_NAV_IMPACT_WIC',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
