# Generated by Django 2.0.10 on 2019-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0034_auto_20190301_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLevelNAVImpacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TradeGroup', models.CharField(max_length=300)),
                ('ticker', models.CharField(max_length=200)),
                ('PM_BASE_CASE', models.FloatField(null=True)),
                ('Outlier', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_AED', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_ARB', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_CAM', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_LEV', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_LG', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_MACO', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_MALT', models.FloatField(null=True)),
                ('BASE_CASE_NAV_IMPACT_TAQ', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_AED', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_ARB', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_CAM', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_LEV', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_LG', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_MACO', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_MALT', models.FloatField(null=True)),
                ('OUTLIER_NAV_IMPACT_TAQ', models.FloatField(null=True)),
            ],
        ),
    ]
