# Generated by Django 2.0.10 on 2019-03-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0036_positionlevelnavimpacts_calculated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionlevelnavimpacts',
            old_name='ticker',
            new_name='Ticker',
        ),
    ]
