# Generated by Django 2.0.10 on 2019-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_reporting', '0037_auto_20190306_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionlevelnavimpacts',
            name='LastPrice',
            field=models.FloatField(null=True),
        ),
    ]
