# Generated by Django 2.0.13 on 2019-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExposuresSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fund', models.CharField(max_length=10)),
                ('sleeve', models.CharField(max_length=30)),
                ('bucket', models.CharField(max_length=30)),
                ('tradegroup', models.CharField(max_length=100)),
                ('longshort', models.CharField(max_length=10)),
                ('alpha_exposure', models.FloatField(null=True)),
                ('hedge_exposure', models.FloatField(null=True)),
                ('net_exposure', models.FloatField(null=True)),
                ('gross_exposure', models.FloatField(null=True)),
                ('capital', models.FloatField(null=True)),
                ('directional_equity_risk', models.FloatField(null=True)),
                ('directional_credit_risk', models.FloatField(null=True)),
                ('directional_ir_risk', models.FloatField(null=True)),
            ],
        ),
    ]
