# Generated by Django 2.0.10 on 2019-02-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposuressnapshot',
            name='bucket',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
