# Generated by Django 2.0.10 on 2019-02-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exposures', '0002_exposuressnapshot_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='alpha_exposure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='capital',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='directional_credit_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='directional_equity_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='directional_ir_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='gross_exposure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='hedge_exposure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exposuressnapshot',
            name='net_exposure',
            field=models.FloatField(null=True),
        ),
    ]
