# Generated by Django 2.0.13 on 2019-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_details', models.FileField(null=True, upload_to='')),
                ('aws_file_key', models.TextField(null=True)),
                ('aws_bucket', models.CharField(max_length=63)),
                ('requested_delete_at', models.DateField(null=True)),
                ('deleted_from_aws_at', models.DateField(null=True)),
            ],
        ),
    ]
