# Generated by Django 2.0.13 on 2019-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=1000)),
                ('article', models.TextField()),
                ('tickers', models.CharField(max_length=1000)),
            ],
        ),
    ]
