# Generated by Django 2.0.10 on 2019-01-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageYTDPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve', models.CharField(max_length=100, null=True)),
                ('tradegroup', models.CharField(max_length=120)),
                ('long_short', models.CharField(max_length=10, null=True)),
                ('inception_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('ytd_dollar', models.FloatField(null=True)),
            ],
        ),
    ]
