# Generated by Django 2.0.13 on 2019-04-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageYTDPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=100)),
                ('sleeve', models.CharField(max_length=100, null=True)),
                ('catalyst_wic', models.CharField(max_length=40, null=True)),
                ('tradegroup', models.CharField(max_length=120)),
                ('long_short', models.CharField(max_length=10, null=True)),
                ('inception_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('ytd_dollar', models.FloatField(null=True)),
                ('fund_aum', models.FloatField(null=True)),
                ('pnl_bps', models.FloatField(null=True)),
            ],
        ),
    ]
