# Generated by Django 2.0.10 on 2019-01-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_pnl_impacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrageytdperformance',
            name='fund',
            field=models.CharField(default='ARB', max_length=100),
            preserve_default=False,
        ),
    ]
