# Generated by Django 2.0.13 on 2019-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_pnl_impacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnlMonitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=50)),
                ('investable_assets', models.CharField(max_length=50)),
                ('ann_gross_pnl_target_perc', models.CharField(max_length=50)),
                ('gross_ytd_return', models.CharField(max_length=50)),
                ('ytd_pnl_perc_target', models.CharField(max_length=50)),
                ('time_passed', models.CharField(max_length=50)),
                ('ann_gross_pnl_target_dollar', models.CharField(max_length=50)),
                ('gross_ytd_pnl', models.CharField(max_length=50)),
                ('ann_loss_budget_perc', models.CharField(max_length=50)),
                ('ytd_total_loss_perc_budget', models.CharField(max_length=50)),
                ('ann_loss_budget_dollar', models.CharField(max_length=50)),
                ('ytd_closed_deal_losses', models.CharField(max_length=50)),
                ('ytd_active_deal_losses', models.CharField(max_length=50)),
                ('last_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
