# Generated by Django 2.0.13 on 2019-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_pnl_impacts', '0003_auto_20190426_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnlLossBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=50)),
                ('loss_budget', models.FloatField(default=None)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PnlProfitTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=50)),
                ('profit_target', models.FloatField(default=None)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
